import { getBillingData } from "@/actions/billing";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { PrintButton } from "@/components/print-button";

export default async function BillingPage() {
  const billingData = await getBillingData();

  return (
    <div className="space-y-8 print:m-0 print:space-y-4">
      <div className="flex justify-between items-center print:hidden">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Billing & Invoices</h1>
          <p className="text-muted-foreground">Automatically generated based on approved Proof of Work.</p>
        </div>
      </div>

      <div className="grid gap-8">
        {billingData.length === 0 ? (
          <p className="text-muted-foreground">No projects found for billing.</p>
        ) : (
          billingData.map((project) => (
            <Card key={project.id} className="print:shadow-none print:border-none print:break-inside-avoid">
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <div>
                  <CardTitle className="text-2xl">{project.name}</CardTitle>
                  <CardDescription>Client: {project.customers?.name}</CardDescription>
                </div>
                {Number(project.totalAmount) >= 0 && (
                  <PrintButton />
                )}
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Hourly Rate</p>
                    <p className="text-2xl font-bold">${Number(project.hourly_rate || 0).toFixed(2)}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Approved Tasks</p>
                    <p className="text-2xl font-bold">{project.approvedActivitiesCount}</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Billable Hours</p>
                    <p className="text-2xl font-bold">{project.totalHours.toFixed(2)}h</p>
                  </div>
                  <div>
                    <p className="text-sm font-medium text-muted-foreground">Total Due</p>
                    <p className="text-2xl font-bold text-primary">${project.totalAmount.toFixed(2)}</p>
                  </div>
                </div>
                
                <div className="mt-8 pt-6 border-t print:block hidden">
                  <p className="text-sm text-center text-muted-foreground">Generated by Pejotinha SaaS Proof of Work Engine. All hours listed above have been cryptographically and visually verified by the client.</p>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
